### ISSUE TITLE
Wheaties Milestone

### ISSUE THREAD

**Issue by kookster** [PRX/meta.prx.org#4]
![bailey_wheaties_small](https://cloud.githubusercontent.com/assets/46439/10677749/4970a398-78dc-11e5-81ea-549a7f523519.png)

** Board **
[Issue Board](https://github.com/PRX/feeder.prx.org/pulls#boards?repos=28927287,42479623,41930413,29747841,30990939,2491705,14878382,14878369&milestone=Wheaties-2015-10-30T04:00:00Z)

**Goal**
Ad serving for podcasts hosted elsewhere, including segmented audio.

**Deliverables**
- [ ] Handle segmented audio in a source rss feed
- [ ] Crier deployment, checking the test feed
- [ ] Adzerk setup for test

**Metrics and Targets**
* Can ingest a feed with multiple segments per episode, and use it to generate a feed that inserts pre and mid rolls
